grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_0:
    class: LogisticRegression
    module: sklearn.linear_model
    params:
      fit_intercept: true
    search_param_grid:
      fit_intercept:
        - true
  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      min_samples_leaf: 2
    search_param_grid:
      min_samples_leaf:
        - 4
        - 6
        - 12
      n_estimators:
        - 100
        - 300
        - 500
        - 800
        - 1000
      criterion:
        - gini
        - entropy
  module_2:
    class: GaussianNB
    module: sklearn.naive_bayes
    params:
      var_smoothing: 0.000000001
    search_param_grid:
      var_smoothing:
        - 0.00000001
        - 0.000000001
        - 0.00000001
